name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-22.04"]

    steps:
      - uses: actions/checkout@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD_FRONTEND: "build"
          CIBW_ENVIRONMENT: "PATH=\"$PATH:$HOME/.cargo/bin\""

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl